filters:
  - filter_type: dir
    file_format: PO
    source_file_extension: po
    source_language: en
    source_file_dir: /locale/en/LC_MESSAGES/
    translation_files_expression: /locale/<lang>/LC_MESSAGES/
